name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb: [4.4]
        ruby: [2.7, "3.0", 3.1, 3.2]
        gemfile:
          - carrierwave-2.1
          - carrierwave-2.2
          - mongoid-7
          - mongoid-8
          - mongoid-9
        include:
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-0.10" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-0.11" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-1.1" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-1.2" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-1.3" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-2.0" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-3" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-4" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-5" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-6" }
    name: Ruby ${{ matrix.ruby }} with ${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Set up MongoDB ${{ matrix.mongodb }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: cat /home/runner/work/carrierwave-mongoid/carrierwave-mongoid/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/mimemagic-0.4.3/gem_make.out
        if: ${{ failure() }}
      - run: cat /home/runner/work/carrierwave-mongoid/carrierwave-mongoid/vendor/bundle/ruby/3.0.0/gems/mimemagic-0.4.3/ext/mimemagic/Rakefile
        if: ${{ failure() }}
      - name: Run tests
        run: bundle exec rake
